<?php
include '../admin/db_connect.php';
$result=  mysql_query("SELECT * FROM tbl_image WHERE category='slider'");

?>
<html>
<head>
	<title>Image carousel generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image carousel" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body style="background-color:#f0f0f0;margin:auto">
	
	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
        <div id="wowslider-container1" style="width:100%; height:360px;">
	<div class="ws_images" style="width:100%; height:360px;">
            <ul>
                <?php while($row=  mysql_fetch_array($result)){?>
                <li>
                    <img  style="width:100%; height:400px;" src="../admin/<?php echo $row['image'];?>" alt="s;ider_4" title="slider_4" id="wows1_0"/>
                </li>
                <?php }?>
            </ul>
        </div>
	<div class="ws_bullets">
            <div>
		<a href="#" title="s;ider_4"><img src="data1/tooltips/sider_4.jpg" alt="s;ider_4"/>1</a>
		<a href="#" title="slider_1"><img src="data1/tooltips/slider_1.jpg" alt="slider_1"/>2</a>
		<a href="#" title="slider_2"><img src="data1/tooltips/slider_2.jpg" alt="slider_2"/>3</a>
		<a href="#" title="slider_3"><img src="data1/tooltips/slider_3.jpg" alt="slider_3"/>4</a>
	</div></div><span class="wsl"><a href="http://wowslider.com/vu">image carousel</a> by WOWSlider.com v7.2</span>
	<div class="ws_shadow"></div>
	
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

</body>
</html>